#!/bin/bash -eu
#
# Run basic test
#

function out()
{
	local rc=${?}

	if [ "${rc}" -ne 0 ] ; then
		echo "FAILED" >&2
	else
		echo "PASSED"
	fi
}

function run_test()
{
	local t=${1}

	echo "-- Run ${t}"

	# Run the tests
	case "${t}" in
		module-config-show)
			# Test a random collection of modules
			for mod in iwlwifi xt_tcpudp cmac intel_rapl_common \
			           crct10dif_pclmul rapl wmi_bmof rc_core drm i2c_smbus \
			           pinctrl_intel ; do
				./kconfig-cli -l 1 -s tests/linux module-config-show "${mod}"
			done
			;;
		*)
			./kconfig-cli -l 1 -s tests/linux "${t}" > .result
			;;
	esac > .result

	# Check the test results
	diff .result tests/data/"${t}"
}

trap out EXIT INT TERM HUP

tests=(
	symbol-list
	help-list
	module-config-show
)

for t in "${tests[@]}" ; do
	run_test "${t}"
done
